#!/bin/bash

conv-commit() {
  if (($# == 0)); then
    echo "options available: feat, fix, chore, ci, test, refactor, wip"
  elif (($# == 2)); then
    message="$(tr '[:upper:]' '[:lower:]' <<<${2:0:1})${2:1}"
    if [[ ${#message} -gt 100 ]]; then
      echo "message longer than 100 characters, (${#message})"
    else
      git commit -m "$1: $message"
    fi
  elif (($# == 3)); then
    message="$(tr '[:upper:]' '[:lower:]' <<<${3:0:1})${3:1}"
    if [[ ${#message} -gt 100 ]]; then
      echo "message longer than 100 characters, (${#message})"
    else
      git commit -m "$1(FCPS-$2): $message"
    fi
  else
    echo 'Wrong number of args'
  fi
}

feat() {
  conv-commit feat "$@"
}

fix() {
  conv-commit fix "$@"
}

chore() {
  conv-commit chore "$@"
}

ci() {
  conv-commit ci "$@"
}

style() {
  conv-commit style "$@"
}

test() {
  conv-commit test "$@"
}

refactor() {
  conv-commit refactor "$@"
}

wip() {
  conv-commit wip "$@"
}
